name: flarte
base: core22
version: '0.3.3'
icon: assets/flarte.png
summary: View and download video from arte.tv catch up TV site
description: |
  An alternative GUI to browse arte.tv website that allows you, not only
  to watch every video but to download them too

contact: solstice.dhiver@gmail.com
issues: https://github.com/solsticedhiver/flarte/issues
source-code: https://github.com/solsticedhiver/flarte
license: GPL-3.0-or-later
grade: devel
confinement: strict
architectures:
  - build-on: [ amd64 ]

parts:
  libmpv:
    source: https://github.com/mpv-player/mpv.git
    source-type: git
    source-tag: v0.36.0
    plugin: meson
    meson-parameters: ['-Dbuild-date=false', '-Dlibmpv=true', '-Dcplayer=false', '--prefix=/usr']
    build-packages:
      - libavcodec-dev
      - libavfilter-dev
      - libass-dev
      - libavformat-dev
      - libavutil-dev
      - libswresample-dev
      - libswscale-dev
      - libasound2-dev
      - libpulse-dev
      - libgl-dev
      - libegl-dev
      - libglx-dev
      - pkg-config
    stage:
      - "usr/include/mpv/*"
      - "usr/lib/$SNAPCRAFT_ARCH_TRIPLET/*"
  flarte:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    flutter-channel: stable
    build-packages: [pkg-config, ninja-build, cmake, libgtk-3-dev]
    build-environment: # WTF: libmpv.so.2 is not found without this
      - LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      #- LDFLAGS: "$LDFLAGS -L$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
    stage-packages: [libblas3, liblapack3, ffmpeg]
    after:
      - libmpv
  cleanup:
    after:
      - flarte
    plugin: nil
    override-prime: |
      find $SNAPCRAFT_PRIME/usr/lib -type f,l -name 'libLLVM-*.so*' -delete
apps:
  flarte:
    command: flarte
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - wayland
      - x11
      - home
      - audio-playback
      - opengl
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack
