name: App Linux Release

on:
  push:
    branches: [ main ]

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Fetch all history for all tags and branches
      if: ${{ !env.ACT }}
      run: |
        git fetch --prune --depth=1000
    - name: change working dir [act]
      if: ${{ env.ACT }}
      run: cd /home/solstice/prog/dvcs/flarte
    - name: Create version
      id: version
      run: echo "version=v$(grep ^version pubspec.yaml |cut -f 2 -d ' '|cut -f 1 -d '+')" >> $GITHUB_OUTPUT
  build:
    name: Build and Create release
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel : 'stable'
        cache: true
    - name: mark flutter git repo as safe [act]
      if: ${{ env.ACT }}
      run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-*
    - name: use apt-cacher-ng proxy [act]
      if: ${{ env.ACT }}
      run: sudo echo 'Acquire::http::Proxy "http://192.168.44.106:3142";'> /etc/apt/apt.conf.d/01acng
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev libmpv-dev mpv
    - run: flutter pub get
    #- run: flutter test
    - run: flutter config --enable-linux-desktop
    - name: install cmake [act]
      if: ${{ env.ACT }}
      run: sudo apt install -y cmake clang
    - run: flutter build linux --release
    - run: mv build/linux/x64/release/bundle build/linux/x64/release/flarte/
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'tar'
        directory: 'build/linux/x64/release/'
        path: 'flarte'
        filename: 'linux_x64.tar.gz'
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      if: ${{ !env.ACT }}
      with:
        allowUpdates: true
        artifacts: 'build/linux/x64/release/linux_x64.tar.gz'
        token: "${{ secrets.GH_TOKEN }}"
        tag: "${{ needs.version.outputs.output1 }}"
        commit: "${{ github.sha }}"
