name: App Linux Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and create linux release
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --depth=1000
    - name: Create version
      id: version
      run: echo "version=$(grep ^version pubspec.yaml |cut -f 2 -d ' '|cut -f 1 -d '+')" >> $GITHUB_OUTPUT
    - uses: subosito/flutter-action@v2
      with:
        channel : 'stable'
        cache: true
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev libmpv-dev mpv
    - run: flutter pub get
    #- run: flutter test
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux --release
    - run: mv build/linux/x64/release/bundle build/linux/x64/release/flarte-${{ steps.version.outputs.version }}/
    - name: Archive release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'tar'
        directory: 'build/linux/x64/release/'
        path: 'flarte-${{ steps.version.outputs.version }}'
        filename: 'flarte-linux_x64.tar.gz'
    - name: Create a release in GitHub
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: 'build/linux/x64/release/flarte-linux_x64.tar.gz'
        token: "${{ secrets.GH_TOKEN }}"
        tag: "v${{ steps.version.outputs.version }}"
        commit: "${{ github.sha }}"
